org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=26.3

# Mod
mod_version=1.7.4.1+mc26.3
maven_group=com.threecolumnsstudio.simplegunpowder
mod_id=simplegunpowder

# Fabric
fabric_loader_version=0.19.5
fabric_loom_version=1.17-SNAPSHOT
fabric_api_version=0.160.5+26.3
sponge_mixin_version=0.17.3+mixin.0.8.7

# NeoForge
# Check latest at https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.3.0.1-beta
