modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "simplegunpowder"
version = "${file.jarVersion}"
displayName = "Simple Gunpowder"
description = '''
A lightweight mod that adds gunpowder recipes and villager trades for easier gunpowder acquisition.
'''
logoFile = "assets/simplegunpowder/icon.png"

[[mixins]]
config = "simplegunpowder.mixins.json"

[[dependencies.simplegunpowder]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplegunpowder]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"