modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "simplegunpowder"
version = "${file.jarVersion}"
displayName = "Simple Gunpowder"
description = '''
Adds gunpowder recipes and villager trades, including a bulk recipe for large amounts of gunpowder — ideal for fireworks and TNT, without relying on creeper farms or mob grinding.
'''
logoFile = "assets/simplegunpowder/icon.png"

[[mixins]]
config = "simplegunpowder.mixins.json"

[[dependencies.simplegunpowder]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplegunpowder]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"